### ISSUE TITLE
Recommended caching strategy ?

### ISSUE THREAD

**Issue by iamake** [ramsaylanier/wordexpress-schema#23]
I'm evaluating this library for production environment. Do you have any recommended caching strategy ?

Technical requirements:
1) As a web developer connecting to the Wordpress GraphQL, I want the lowest latency from the service
2) As a web developer connecting to the Wordpress GraphQL, I want only necessary data to be used in the frontend

How could the GraphQL service developer achieve these requirements.

Placing cache in front of the GraphQL service would not satisfy the requirements if there are similar queries with different fields e.g.

```
post(id: $post_id) {
   post_id
   post_title
   post_excerpt
}
```

```
post(id: $post_id) {
   post_id
   post_title
   post_content
}
```

Maybe, placing cache at data retrieval level could be a solution. However, I don't find a good way to do that yet. Any recommendation ?

**Comment by ramsaylanier** [comment]
Caching strategy is probably outside the realm of this package, since this package simply provides a schema and ways to access the data. Caching is going to happen on a) the client b) the server or c) both. 

For client-side caching, I'd recommend taking a look at [Apollo Client](https://github.com/apollographql/apollo-client). For server-side caching, I'd imagine the caching layer would be outside of the graphql layer. Take a look at [this issue](https://github.com/graphql/graphql-js/issues/819).

Im going to close this issue as it is outside the purview of this package.
